### ISSUE TITLE
Heimdall / delivery install failing

### ISSUE THREAD

**Issue by Franzferdinan51** [bttcprotocol/delivery#4] opened 2021-12-23 19:52 UTC
**Heimdall version** (use `heimdall version` or `git rev-parse --verify HEAD` if installed from source): n/a

**Environment**: cli
- **OS** (e.g. from /etc/os-release): ubuntu 20.04
- **Install tools**: make
- **Others**:

**What happened**:
during make install it fails with the following right before fail

debugger.go:22:13: warning: ‘_duk_debugger_attach’ defined but not used [-Wunused-function]
mv /bin/heimdalld /bin/deliveryd
mv: cannot stat '/bin/heimdalld': No such file or directory
make: *** [Makefile:41: install] Error 1

**What you expected to happen**: the install to complete 

**Have you tried the latest version**: yes/no yes

**How to reproduce it** (as minimally and precisely as possible):
nothing special was done outside of a standard install after git pull 

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

sudo make install
go install -ldflags '-X github.com/bttcprotocol/delivery/version.Name=delivery -X github.com/bttcprotocol/delivery/version.ServerName=deliveryd -X github.com/bttcprotocol/delivery/version.ClientName=deliverycli -X github.com/bttcprotocol/delivery/version.Version=1.0.0 -X github.com/bttcprotocol/delivery/version.Commit=eaaf7fea8b80819a327bea478f942dd303728242 -X github.com/cosmos/cosmos-sdk/version.Name=delivery -X github.com/cosmos/cosmos-sdk/version.ServerName=deliveryd -X github.com/cosmos/cosmos-sdk/version.ClientName=deliverycli -X github.com/cosmos/cosmos-sdk/version.Version=1.0.0 -X github.com/cosmos/cosmos-sdk/version.Commit=eaaf7fea8b80819a327bea478f942dd303728242' ./cmd/heimdalld
# gopkg.in/olebedev/go-duktape.v3
In file included from _cgo_export.c:4:
debugger.go:22:13: warning: ‘_duk_debugger_attach’ defined but not used [-Wunused-function]
go install -ldflags '-X github.com/bttcprotocol/delivery/version.Name=delivery -X github.com/bttcprotocol/delivery/version.ServerName=deliveryd -X github.com/bttcprotocol/delivery/version.ClientName=deliverycli -X github.com/bttcprotocol/delivery/version.Version=1.0.0 -X github.com/bttcprotocol/delivery/version.Commit=eaaf7fea8b80819a327bea478f942dd303728242 -X github.com/cosmos/cosmos-sdk/version.Name=delivery -X github.com/cosmos/cosmos-sdk/version.ServerName=deliveryd -X github.com/cosmos/cosmos-sdk/version.ClientName=deliverycli -X github.com/cosmos/cosmos-sdk/version.Version=1.0.0 -X github.com/cosmos/cosmos-sdk/version.Commit=eaaf7fea8b80819a327bea478f942dd303728242' ./cmd/heimdallcli
# gopkg.in/olebedev/go-duktape.v3
In file included from _cgo_export.c:4:
debugger.go:22:13: warning: ‘_duk_debugger_attach’ defined but not used [-Wunused-function]
go install -ldflags '-X github.com/bttcprotocol/delivery/version.Name=delivery -X github.com/bttcprotocol/delivery/version.ServerName=deliveryd -X github.com/bttcprotocol/delivery/version.ClientName=deliverycli -X github.com/bttcprotocol/delivery/version.Version=1.0.0 -X github.com/bttcprotocol/delivery/version.Commit=eaaf7fea8b80819a327bea478f942dd303728242 -X github.com/cosmos/cosmos-sdk/version.Name=delivery -X github.com/cosmos/cosmos-sdk/version.ServerName=deliveryd -X github.com/cosmos/cosmos-sdk/version.ClientName=deliverycli -X github.com/cosmos/cosmos-sdk/version.Version=1.0.0 -X github.com/cosmos/cosmos-sdk/version.Commit=eaaf7fea8b80819a327bea478f942dd303728242' bridge/bridge.go
# gopkg.in/olebedev/go-duktape.v3
In file included from _cgo_export.c:4:
debugger.go:22:13: warning: ‘_duk_debugger_attach’ defined but not used [-Wunused-function]
mv /bin/heimdalld /bin/deliveryd
mv: cannot stat '/bin/heimdalld': No such file or directory
make: *** [Makefile:41: install] Error 1

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by xq-lu** [comment] 2021-12-24 04:16
> paste

hi,Franzferdinan51 

could you check if you set $GOPATH correctly, as per my experience if this option GOPATH was not set or set unproperly, this error will occurs 

`echo $GOPATH
/home/java-tron/go
 which deliveryd
~/go/bin/deliveryd`

**Comment by vivian-kang** [comment] 2023-07-13 04:03
Thanks for your contribution to BTTC, this issue will be closed as no update for a long time.

Please feel free to re-open it if the issue is not resolved, thanks.

**Closed by vivian-kang** 2023-07-13 04:03 UTC
